server:
  port: 8081
spring:
  application:
    name: bot-service
  # redis配置，以下有默认配置的也可以使用默认配置
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-idle: 8 # 连接池中的最大空闲连接 默认 8
      min-idle: 0 # 连接池中的最小空闲连接 默认 0
    timeout: 5000 # 连接超时时间（毫秒）
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
logging:
  config: classpath:logback.xml
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999

# 新闻接口配置文件
news:
  key: Vb7D+4YwGN3+jJmK+48yT2zFOwTgsJeZ/px16A
# 机器人集群得配置 可以配置多个 配置详情详见LaomuBot
laomubot:
  laomuBots:
    - postPort: 31091
      socketPort: 31092
      botName: bot1
      ipAddr: 127.0.0.1
      debug: true
      useAsyncCommands: true
  # - postPort: 31090
  #   botName: bot2
  #   ipAddr: 127.0.0.1

