server:
  port: 8181
spring:
  application:
    name: laomuwms-store
  # redis配置，以下有默认配置的也可以使用默认配置
  redis:
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-idle: 8 # 连接池中的最大空闲连接 默认 8
      min-idle: 0 # 连接池中的最小空闲连接 默认 0
    timeout: 5000 # 连接超时时间（毫秒）
  datasource:
    url: jdbc:mysql://192.168.162.128:33306/wms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  config: classpath:logback.xml

