server:
  port: 9501
spring:
  application:
    name: mail-service
  mail:
    protocol: smtp
    # host: smtp.qq.com #SMTP服务器地址
    # username: 820252044@qq.com #登陆账号
    # password: ffbuuqyggmzebbjj #登陆密码（或授权码）
    # properties:
      # from: 820252044@qq.com #邮件发信人（即真实邮箱）
    host: smtp.163.com #SMTP服务器地址
    username: 13329418250 #登陆账号
    password: xm8aaaa #登陆密码（或授权码）
    properties:
      from: 13329418250@163.com #邮件发信人（即真实邮箱）
    default-encoding: utf-8
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量
  datasource:
    url: jdbc:mysql://localhost:3306/kuq
    username: root
    password: root
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 设置org.springframework包的日志级别为debug
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
